// Catalogo curado de iconos de linea (lucide-react) para las categorias.
// Fase 0 del PLAN-iconos.md -- todavia NO se usa para pintar categorias; solo
// existe para que las fases B lo consuman.
//
// IMPORTS EXPLICITOS Y NOMBRADOS a proposito: nunca `import * as lucide`. Asi
// el tree-shaking del build solo incluye estos ~159 iconos y no los ~2000
// que trae la libreria (el bundle ya arrastra un warning de tamano).
//
// Nombres: se usa la convencion kebab-case de lucide.dev como clave publica
// (la misma que guardara `categorias.icono` en la BD y el CASE del SQL). El
// componente React correspondiente es el PascalCase de ese nombre.
//
// Verificado nombre a nombre contra lucide-react ^1.31.0 (el instalado). Ojo
// con nombres que cambian entre versiones: aqui ya se aplican los de la 1.x --
//   'tree-palm'      (era 'palmtree')
//   'ellipsis'       (era 'more-horizontal')
//   'car-taxi-front' (era 'taxi-front')

import {
  Activity,
  Apple,
  Armchair,
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowUpRight,
  Baby,
  Backpack,
  BadgePercent,
  Bandage,
  Banknote,
  Bath,
  Bed,
  Beer,
  Bike,
  Bird,
  Bone,
  Book,
  BookOpen,
  Bookmark,
  Box,
  Brain,
  Briefcase,
  Building2,
  Bus,
  Cake,
  Calculator,
  Camera,
  Candy,
  Car,
  CarTaxiFront,
  Carrot,
  Cat,
  CircleDashed,
  Clapperboard,
  ClipboardList,
  Coffee,
  Coins,
  Compass,
  Cookie,
  CreditCard,
  Cross,
  Dice5,
  Dog,
  DoorOpen,
  Drama,
  Droplet,
  Drumstick,
  Dumbbell,
  Egg,
  Ellipsis,
  Factory,
  Film,
  Fish,
  Flame,
  Folder,
  Footprints,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Guitar,
  Ham,
  Hammer,
  HandCoins,
  HandHeart,
  HardHat,
  Hash,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  Hotel,
  House,
  IceCreamCone,
  Key,
  Lamp,
  Landmark,
  Laptop,
  Leaf,
  Luggage,
  Map,
  MapPin,
  Milk,
  Mountain,
  Music,
  Package,
  Paintbrush,
  Palette,
  ParkingMeter,
  PartyPopper,
  PawPrint,
  PenTool,
  Phone,
  Piano,
  PiggyBank,
  Pill,
  Pin,
  Pizza,
  Plane,
  Plug,
  Presentation,
  Puzzle,
  Rabbit,
  Receipt,
  Recycle,
  Refrigerator,
  Router,
  Ruler,
  Salad,
  SatelliteDish,
  ScanBarcode,
  Scissors,
  Shapes,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  ShowerHead,
  Smile,
  Snowflake,
  Sofa,
  Soup,
  Sparkles,
  Sprout,
  Squirrel,
  Star,
  Stethoscope,
  Store,
  Sun,
  Syringe,
  Tablets,
  Tag,
  Tent,
  Thermometer,
  Ticket,
  TrainFront,
  Trash2,
  TreePalm,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  User,
  Users,
  Utensils,
  UtensilsCrossed,
  Wallet,
  WashingMachine,
  Watch,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from 'lucide-react'

// Los 12 grupos del plan. El orden es el de presentacion en el futuro selector.
// Un mismo icono puede aparecer en dos grupos (p. ej. 'plane', 'tag'); ICONOS
// lo colapsa a una sola entrada.
export const GRUPOS_ICONOS = [
  { clave: 'comida', iconos: ['utensils', 'utensils-crossed', 'coffee', 'pizza', 'apple', 'beer', 'wine', 'cake', 'cookie', 'soup', 'fish', 'carrot', 'ham', 'salad', 'egg', 'milk', 'candy', 'drumstick', 'ice-cream-cone'] },
  { clave: 'transporte', iconos: ['car', 'bus', 'train-front', 'bike', 'fuel', 'plane', 'ship', 'car-taxi-front', 'parking-meter', 'truck', 'compass', 'map'] },
  { clave: 'hogar', iconos: ['house', 'sofa', 'bed', 'lamp', 'wrench', 'plug', 'trash-2', 'washing-machine', 'key', 'paintbrush', 'hammer', 'door-open', 'armchair', 'refrigerator', 'shower-head', 'bath'] },
  { clave: 'servicios', iconos: ['zap', 'droplet', 'flame', 'wifi', 'phone', 'tv', 'router', 'recycle', 'satellite-dish', 'thermometer', 'shield'] },
  { clave: 'salud', iconos: ['pill', 'heart-pulse', 'stethoscope', 'cross', 'activity', 'dumbbell', 'glasses', 'brain', 'syringe', 'bandage', 'tablets', 'bone'] },
  { clave: 'ocio', iconos: ['clapperboard', 'music', 'gamepad-2', 'ticket', 'book-open', 'palette', 'camera', 'headphones', 'party-popper', 'dice-5', 'film', 'drama', 'guitar', 'puzzle', 'trophy', 'piano'] },
  { clave: 'compras', iconos: ['shopping-cart', 'shopping-bag', 'shirt', 'gift', 'tag', 'store', 'gem', 'watch', 'footprints', 'scissors', 'badge-percent', 'scan-barcode'] },
  { clave: 'finanzas', iconos: ['piggy-bank', 'banknote', 'credit-card', 'wallet', 'coins', 'landmark', 'trending-up', 'receipt', 'hand-coins', 'arrow-left-right', 'arrow-down-left', 'arrow-up-right'] },
  { clave: 'trabajo_educacion', iconos: ['briefcase', 'graduation-cap', 'laptop', 'pen-tool', 'presentation', 'building-2', 'book', 'calculator', 'clipboard-list', 'factory', 'hard-hat', 'ruler'] },
  { clave: 'personas_mascotas', iconos: ['users', 'baby', 'paw-print', 'dog', 'cat', 'heart', 'user', 'rabbit', 'bird', 'squirrel', 'hand-heart', 'heart-handshake'] },
  { clave: 'viajes', iconos: ['plane', 'map-pin', 'luggage', 'tent', 'tree-palm', 'mountain', 'hotel', 'backpack', 'globe', 'sun', 'umbrella', 'snowflake'] },
  { clave: 'otros', iconos: ['tag', 'sparkles', 'pin', 'star', 'circle-dashed', 'ellipsis', 'shapes', 'box', 'package', 'folder', 'bookmark', 'hash', 'smile', 'leaf', 'sprout'] },
]

// Mapa nombre (kebab) -> componente de lucide. Unica fuente para resolver un
// icono guardado en datos.
export const ICONOS = {
  'activity': Activity,
  'apple': Apple,
  'armchair': Armchair,
  'arrow-down-left': ArrowDownLeft,
  'arrow-left-right': ArrowLeftRight,
  'arrow-up-right': ArrowUpRight,
  'baby': Baby,
  'backpack': Backpack,
  'badge-percent': BadgePercent,
  'bandage': Bandage,
  'banknote': Banknote,
  'bath': Bath,
  'bed': Bed,
  'beer': Beer,
  'bike': Bike,
  'bird': Bird,
  'bone': Bone,
  'book': Book,
  'book-open': BookOpen,
  'bookmark': Bookmark,
  'box': Box,
  'brain': Brain,
  'briefcase': Briefcase,
  'building-2': Building2,
  'bus': Bus,
  'cake': Cake,
  'calculator': Calculator,
  'camera': Camera,
  'candy': Candy,
  'car': Car,
  'car-taxi-front': CarTaxiFront,
  'carrot': Carrot,
  'cat': Cat,
  'circle-dashed': CircleDashed,
  'clapperboard': Clapperboard,
  'clipboard-list': ClipboardList,
  'coffee': Coffee,
  'coins': Coins,
  'compass': Compass,
  'cookie': Cookie,
  'credit-card': CreditCard,
  'cross': Cross,
  'dice-5': Dice5,
  'dog': Dog,
  'door-open': DoorOpen,
  'drama': Drama,
  'droplet': Droplet,
  'drumstick': Drumstick,
  'dumbbell': Dumbbell,
  'egg': Egg,
  'ellipsis': Ellipsis,
  'factory': Factory,
  'film': Film,
  'fish': Fish,
  'flame': Flame,
  'folder': Folder,
  'footprints': Footprints,
  'fuel': Fuel,
  'gamepad-2': Gamepad2,
  'gem': Gem,
  'gift': Gift,
  'glasses': Glasses,
  'globe': Globe,
  'graduation-cap': GraduationCap,
  'guitar': Guitar,
  'ham': Ham,
  'hammer': Hammer,
  'hand-coins': HandCoins,
  'hand-heart': HandHeart,
  'hard-hat': HardHat,
  'hash': Hash,
  'headphones': Headphones,
  'heart': Heart,
  'heart-handshake': HeartHandshake,
  'heart-pulse': HeartPulse,
  'hotel': Hotel,
  'house': House,
  'ice-cream-cone': IceCreamCone,
  'key': Key,
  'lamp': Lamp,
  'landmark': Landmark,
  'laptop': Laptop,
  'leaf': Leaf,
  'luggage': Luggage,
  'map': Map,
  'map-pin': MapPin,
  'milk': Milk,
  'mountain': Mountain,
  'music': Music,
  'package': Package,
  'paintbrush': Paintbrush,
  'palette': Palette,
  'parking-meter': ParkingMeter,
  'party-popper': PartyPopper,
  'paw-print': PawPrint,
  'pen-tool': PenTool,
  'phone': Phone,
  'piano': Piano,
  'piggy-bank': PiggyBank,
  'pill': Pill,
  'pin': Pin,
  'pizza': Pizza,
  'plane': Plane,
  'plug': Plug,
  'presentation': Presentation,
  'puzzle': Puzzle,
  'rabbit': Rabbit,
  'receipt': Receipt,
  'recycle': Recycle,
  'refrigerator': Refrigerator,
  'router': Router,
  'ruler': Ruler,
  'salad': Salad,
  'satellite-dish': SatelliteDish,
  'scan-barcode': ScanBarcode,
  'scissors': Scissors,
  'shapes': Shapes,
  'shield': Shield,
  'ship': Ship,
  'shirt': Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'shower-head': ShowerHead,
  'smile': Smile,
  'snowflake': Snowflake,
  'sofa': Sofa,
  'soup': Soup,
  'sparkles': Sparkles,
  'sprout': Sprout,
  'squirrel': Squirrel,
  'star': Star,
  'stethoscope': Stethoscope,
  'store': Store,
  'sun': Sun,
  'syringe': Syringe,
  'tablets': Tablets,
  'tag': Tag,
  'tent': Tent,
  'thermometer': Thermometer,
  'ticket': Ticket,
  'train-front': TrainFront,
  'trash-2': Trash2,
  'tree-palm': TreePalm,
  'trending-up': TrendingUp,
  'trophy': Trophy,
  'truck': Truck,
  'tv': Tv,
  'umbrella': Umbrella,
  'user': User,
  'users': Users,
  'utensils': Utensils,
  'utensils-crossed': UtensilsCrossed,
  'wallet': Wallet,
  'washing-machine': WashingMachine,
  'watch': Watch,
  'wifi': Wifi,
  'wine': Wine,
  'wrench': Wrench,
  'zap': Zap,
}

// Icono de respaldo cuando un nombre no esta en el catalogo (emoji sin
// equivalente, dato corrupto, version vieja). Decision del plan: 'tag'.
export const ICONO_FALLBACK = 'tag'

// Resuelve un nombre a su componente. Siempre devuelve un componente valido:
// si `nombre` no esta en el catalogo, cae a ICONO_FALLBACK ('tag').
export function resolverIcono(nombre) {
  return ICONOS[nombre] ?? ICONOS[ICONO_FALLBACK]
}
